const emptyWishlistCTA = 'LOOKS LIKE YOUR WISHLIST NEEDS WISHES'

Cypress.env('viewports').forEach((viewport) => {
    describe(`Header heart icon: ${viewport.device} (${viewport.width} x ${viewport.height})`, () => {
        beforeEach(function () {
            cy.viewport(viewport.width, viewport.height)
            cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
            cy.visit(Cypress.env('baseURL'))
            cy.closeAttn()
        })
        it(`If I'm logged in and click the heart in the nav, I am forwarded to the wishlist portal and see a grid of my wishlists displayed`, function () {
            cy.login('user-login')
            cy.step('click wishlist icon')
            cy.get('.add-to-wishlist-btn[data-wish-action="viewWishlists"]').click()
            cy.url()
                .should('include', '/pages/wishlists')
            cy.get('swym-wishlist-portal')
                .should('be.visible')
        })
        it('If I have no wishlists at all, I see a message and a CTA to create a new wishlist', function () {
            cy.login('blank-user')
            cy.step('click wishlist icon')
            cy.get('.add-to-wishlist-btn[data-wish-action="viewWishlists"]').click()
            cy.url()
                .should('include', '/pages/wishlists')
            cy.get('swym-wishlist-portal').find('h3').contains(emptyWishlistCTA, { matchCase: false })
                .should('be.visible')
            // test fails because when i delete the only wishlist, the next time i sign in it's there again
        })
        it(`Create new wishlist`, function () {
            cy.login('user-login')
            cy.step('click wishlist icon')
            cy.get('.add-to-wishlist-btn[data-wish-action="viewWishlists"]').click()
            cy.section('I can click the create wishlist button in the top right and see the drawer animate in to create a new wishlist')
            cy.step('click new wishlist button')
            cy.get('button').contains('New Wishlist', { matchCase: false }).click()
            cy.get('div#headlessui-dialog-overlay-P0-0')
                .should('be.visible')
                .and('have.attr', 'data-headlessui-state', 'open')
            cy.section('I can enter a wishlist name and click the CTA to submit the form')
            cy.step('type wishlist name')
            cy.get('h2').contains('WISHLIST NAME', { matchCase: false }).parent('section').siblings('section').first().find('form').within(() => {
                cy.get('input').type('test list')
                cy.step('click create wishlist')
                cy.get('button').click()
            })
            cy.section(`I am forwarded to the newly created wishlist's detail page`)
            cy.url()
                .should('include', 'lid')
            cy.get('span').contains('test list')
                .should('be.visible')
            cy.section('I see some text saying wishlist is empty')
            cy.get('h3').contains('empty', { matchCase: false }).as('empty')
                .should('be.visible')
            cy.section('I see a CTA linking to the home page')
            cy.get('@empty').siblings('a')
                .should('be.visible')
                .click()
            cy.url()
                .should('eq', 'https://www.dollskill.com/')
        })
    })
})