const emptyWishlistCTA = 'LOOKS LIKE YOUR WISHLIST NEEDS WISHES'
const newList = 'test list'

Cypress.env('viewports').forEach((viewport) => {
    describe(`Wishlist portal - Lists page: ${viewport.device} (${viewport.width} x ${viewport.height})`, () => {
        beforeEach(function () {
            cy.viewport(viewport.width, viewport.height)
            cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        })
        it(`If I'm logged in and click the heart in the nav, I am forwarded to the wishlist portal and see a grid of my wishlists displayed`, function () {
            cy.login('wishlist')
            cy.section('main test')
            cy.visit(Cypress.env('baseURL'))
            cy.step('click wishlist icon')
            cy.get('swym-wishlist-btn').click()
            cy.url()
                .should('include', '/pages/wishlists')
            cy.getByData('wishlist-portal--lists--list-grid')
                .should('be.visible')
        })
        it('If I have no wishlists at all, I see a message and a CTA to create a new wishlist', function () {
            cy.login('blank')
            cy.section('main test')
            cy.visit(Cypress.env('wishlistURL'))
            cy.get('swym-wishlist-portal').find('button').first().text().then(btn => {
                if (btn.includes('New')) {
                    cy.section('delete wishlist')
                    cy.getByData('wishlist-portal--lists--list-grid--list').click()
                    cy.step('click delete wishlist button')
                    cy.getByData('wishlist-portal--detail--delete-button').click()
                    cy.step('delete wishlist')
                    cy.getByData('wishlist-drawer--delete').find('button[type="submit"]').click()
                }
                cy.get('swym-wishlist-portal').find('h3').contains(emptyWishlistCTA, { matchCase: false })
                    .should('be.visible')
            })
        })
        it(`Create new wishlist`, function () {
            cy.login('wishlist')
            cy.visit(Cypress.env('wishlistURL'))
            cy.section('I can click the create wishlist button in the top right and see the drawer animate in to create a new wishlist')
            cy.step('click new wishlist button')
            cy.getByData('wishlist-portal--lists--create-wishlist-button').click()
            cy.getByData('wishlist-drawer--create')
                .should('exist')
            cy.section('I can enter a wishlist name and click the CTA to submit the form')
            cy.step('type wishlist name')
            cy.getByData('wishlist-drawer--create--name-input').type(newList)
            cy.step('click create wishlist')
            cy.getByData('wishlist-drawer--create--submit').click()
            cy.section(`I am forwarded to the newly created wishlist's detail page`)
            cy.getByData('wishlist-portal--detail--list-name').contains(newList)
                .should('be.visible')
            cy.section('I see some text saying wishlist is empty')
            cy.get('h3').contains('empty', { matchCase: false }).as('empty')
                .should('be.visible')
            cy.section('I see a CTA linking to the home page')
            cy.get('@empty').siblings('a')
                .should('be.visible')
                .click()
            cy.url()
                .should('eq', 'https://www.dollskill.com/')
            cy.section('reset')
            cy.get('swym-wishlist-btn').click()
            cy.getByData('wishlist-portal--lists--list-grid--list--name').contains(newList).click()
            cy.getByData('wishlist-portal--detail--delete-button').click()
            cy.getByData('wishlist-drawer--delete').find('button').contains('delete', { matchCase: false }).click()
        })
    })
})