Cypress.env('viewports').forEach((viewport) => {
    describe(`Add to cart from PDP: ${viewport.device} (${viewport.width} x ${viewport.height})`, () => {
        beforeEach(() => {
            cy.viewport(viewport.width, viewport.height)
            cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
            cy.visit(Cypress.env('baseURL'))
            // cy.closeAttn()
        })
        it('When I add a specific product variant to cart, the correct variant is added', () => {
            cy.step('go to all new')
            cy.allNew(viewport)
            cy.get('.product-title a').eq(1).as('product').then((product) => {
                const productText = product.text()
                cy.print({ title: 'variable', message: `product: ${productText}`, type: 'var' })
                cy.step('click second product')
                cy.wrap(product).click()
                cy.getByData('pdp--size-box').not('.oos').first().as('size').then((size) => {
                    const sizeText = size.text()
                    cy.print({ title: 'variable', message: `size: ${sizeText}`, type: 'var' })
                    const variant = size.attr('data-vid')
                    cy.print({ title: 'variable', message: `variant: ${variant}`, type: 'var' })
                    cy.step('select size')
                    cy.wrap(size).click()
                    cy.step('add to bag')
                    cy.getByData('pdp--add-to-bag-button').click()
                    cy.getByData('cart--drawer').should('have.class', 'drawer1-open')
                    cy.getByData('cart--cart-item-product-title').first().contains(productText, { matchCase: false }).should('exist')
                    cy.getByData('cart--cart-item-variant').should('have.attr', 'data-vid', variant)
                })
            })
        })
        // cy.print({ title: 'variable', message: `product: ${productText}`, type: 'var' })
        it.only('Pressing the increment and decrement buttons (+ and -) updates the quantity and cart subtotal correctly', () => {
            cy.step('go to all new')
            cy.allNew(viewport)
            cy.step('click second product')
            cy.getByData('product-card').eq(1).click()
            cy.step('select size')
            cy.getByData('pdp--size-box').not('.oos').first().click()
            cy.getByData('pdp--add-to-bag-button').click()
            cy.get('span.product-price').text().then((price) => {
                cy.print({ title: 'variable', message: `price: ${price}`, type: 'var' })
                const priceNum = Number(price.replace('$', ''))
                cy.print({ title: 'variable', message: `price number: ${priceNum}`, type: 'var' })
                cy.get('span.cart-subtotal-amount').as('subtotal').should('contain', price)
                cy.get('div.cart-quantity-adjuster').find('span').not('.toggle-quantity').as('qty').should('contain', 1)
                cy.get('.toggle-quantity[data-type="add"]').click()
                cy.get('@qty').should('contain', 2)
                cy.get('span.product-price').should('contain', priceNum * 2)
                cy.get('@subtotal').should('contain', priceNum * 2)
            })
        })
    })
})